spring:
  datasource:
    url: jdbc:mysql://192.168.1.180:3306/seata-demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: Db_Zz_123_Db_Zz_123_Db_Zz_123_
    driver-class-name: com.mysql.cj.jdbc.Driver

seata:
  tx-service-group: test_tx_service_group
  config:
    type: nacos
    nacos:
      serverAddr: ${spring.cloud.nacos.server-addr}
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.server-addr}
      group: SEATA_GROUP
      username: nacos
      password: nacos